### ISSUE TITLE
Legend keys aren't being removed when switching between lockdown categories

### ISSUE THREAD

**Issue by hobbes7878** [reuters-graphics/chart-module-CountryLockdownIndicatorStrips#3]
![image](https://user-images.githubusercontent.com/2772078/88397559-03d41d80-cdbc-11ea-8260-4e857d8d9f02.png)

**Comment by pkd2512** [comment]
When the chart is redrawn, the data is fully updated, but the props are 'merged' with the new props. This makes a union of the two prop sets, so a new index point gets added, but the old one isn't removed. Help required from @hobbes7878

**Comment by pkd2512** [comment]
Also, I encountered a merge conflict which seems to have reverted the changes done my @hobbes7878 in the rebuild ```b64491a09af62e15aa5d20c064c2fa5acc73e042``` which I have saved in the ```conflict build``` branch. Help required to make this into the master branch and stash the latest commits.

https://github.com/reuters-graphics/chart-module-CountryLockdownIndicatorStrips/commits/conflictbuild

**Comment by pkd2512** [comment]
> b64491a09af62e15aa5d20c064c2fa5acc73e042

Solved using https://stackoverflow.com/a/52741123/7791112

**Comment by hobbes7878** [comment]
Ah, sure. So you can use `assign` instead of `merge` for the props on the base class. Can either use lodash's version, or just normal `Object.assign` should do it.

**Comment by pkd2512** [comment]
```Resolved```

Please update the usage as per the documentation. 
``` If your data update needs an update to legend, specify the max number of items that will be shown and set the items to null wherever not applicable. If you want a legend item to not update as data updates, simply do not mention it in the update props.```

```javascript
this.chart
        .props({
          legendItems: { // should contain items from stripColor
            // null: null,
            // stepLegend: {
            //   0: null,
            //   1: null,
            // },
            indexLegend: {
              0: 'no NONO',
              1: 'recommend closing',
              2: 'require closing on some levels',
              3: 'require closing all levels',
              4: null,
            },
          },
        })
        .draw();
```

**Comment by pkd2512** [comment]
##### A simplification for the legend colours
*If you specify fewer colours than in the legend, it will extrapolate the last colour*

```javascript
stripColor: { // should be numeric values that are mapped from the data
    0: '#4C566A',
    1: '#948072',
    2: '#f68e26',
    3: '#de2d26',
  }```

**Comment by hobbes7878** [comment]
Just tried this and I'm not sure it works.

Here's my legend categories with nulls specified for the max number:
![image](https://user-images.githubusercontent.com/2772078/88454180-9f6d9880-ce65-11ea-8ac7-fa016ca90219.png)

And this is the legend I get now:
![image](https://user-images.githubusercontent.com/2772078/88454169-8b299b80-ce65-11ea-874c-fc4001dad164.png)

**Comment by pkd2512** [comment]
I just checked the country page demo on the app. It seems to be working on the page I think. Did anything change on your end? Because of the transition, the new labels load first and then the topmost div gets removed I see in the demo.

**Comment by pkd2512** [comment]
This might work, in case the JSON null is being read as a string. Check added for filtering out both ```null``` and ``` 'null' ```
